### ISSUE TITLE
Upgrade Tip

### ISSUE THREAD

**Issue by eltoneo** [sraase/arachne-browser#1]
Hi,
I was under the mistaken impression this source codes intension was to compile using DJGPP, WATT32 with openssl for HTTPS support.
e
[link](https://groups.google.com/g/comp.os.msdos.djgpp/c/TPyx9rj9V3g/m/NTE2d7x9CgAJ)

[link](https://groups.google.com/g/comp.os.msdos.djgpp/c/Zj-0PbUKtUE/m/sANNJFahCgAJ)

[link](https://groups.google.com/g/comp.os.msdos.djgpp/c/XehGHeRFjgk/m/qcekzHHACgAJ)

**Comment by sraase** [comment]
Currently, Arachne/DOS is built using Borland C++ 3.1.

DJGPP does not support 8086/80286 processors, and it would be necessary to port LOPIF first. I don't know whether WATT-32 is a drop-in replacement for WATTCP, either. Switching to mTCP looks more interesting, as it is still actively maintained.

I currently do not intend to change the compiler.
