### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by rafael2k** [sraase/arachne-browser#2]
Thanks for keeping Arachne Browser alive!

Do you have any guide on how to compile on Linux?

**Comment by sraase** [comment]
I have not written any official instructions yet, so this will have to do for now. Linux installation is non-trivial.

If you have issues, please ask.

### Instructions for DOS version

Start by downloading and installing the "Arachne v1.99;GPL" DOS package from [https://www.glennmcc.org/arachne/](https://www.glennmcc.org/arachne/), the file is a199gpl.zip. Installation is straight-forward, just follow the instructions.

To compile the DOS version, find yourself a copy of Borland C++ 3.1 and install it. Cross compilation is not supported, but DOSBox can be used.

Open the **CORE.PRJ** (386+), **CORE-086.PRJ** (PC/XT) or **CORE-!87.PRJ** (no FPU) project file and select "Compile > Build all". Replace C:\ARACHNE\CORE.EXE with your new version after compilation is done.

The DOS version is stable.

### Instructions for Linux/BSD version

To compile the SDL2 version, simply go to the "sdl2" folder and run "make". The SVGALIB version (in the "svgalib" folder) should also compile - please file a bug if it doesn't. If possible, create a 32-bit binary (add "-m32" to CFLAGS or use "CC=i686-linux-gnu-gcc" in sdl2/makefile). All Linux builds are quite unstable, but 64-bit builds are particularly bad.

I have not created a package for the support files (fonts, icons, user interface, help and configuration files) yet, so you need to install them manually. Start by downloading the "Arachne GPL v1.95;GPL" Linux package from [https://www.glennmcc.org/aralinux/](https://www.glennmcc.org/aralinux/), the file is **arachne-svgalib-1.95.tgz** (link is at the top of the page). Glenn has maintained Arachne for the last 20-odd years. Thank him.

**Do not run the install script from the archive. Do not run the arachne-install script either.**

From the arachne archive:

- copy man/man1/arachne.1 to /usr/share/man/man1/
- copy doc/arachne/html/* to /usr/share/doc/arachne/html/
- copy share/arachne/gui/* to /usr/share/arachne/gui/
- copy share/arachne/ikons/* to /usr/share/arachne/ikons/
- copy share/arachne/iso-8859-1/* to /usr/share/arachne/iso-8859-1/ (include subfolders)
- copy share/arachne/iso-8859-2/* to /usr/share/arachne/iso-8859-2/ (include subfolders)
- copy share/arachne/mime.conf to /usr/share/arachne/**mime.cfg** (different file name)
- copy share/arachne/templates/toolbar.cfg to /usr/share/arachne/**toolbar.cfg**
- copy share/arachne/templates/entity.cfg to /usr/share/arachne/**entity.cfg**

Edit your new /usr/share/arachne/mime.cfg:

- in [MIME], replace the image/jpeg, image/png and image/x-png MIME types:
```
image/jpeg               JPG>BMP|convert $1 bmp3:$2
image/png                PNG>BMP|convert $1 bmp3:$2
image/x-png              PNG>BMP|convert $1 bmp3:$2
```
- in [ARACHNE], replace the .jpg, .jpe and .png file types:
```
file/.jpg            >BMP|convert $1 bmp3:$2
file/.jpe            >BMP|convert $1 bmp3:$2
file/.png            >BMP|convert $1 bmp3:$2
```

Create a simple configuration file in $HOME/.arachne/arachne.cfg:

```
# Arachne configuration
HomePage http://www.frogfind.com
Multitasking No
HTTPKeepAlive No
```

**Comment by rafael2k** [comment]
Thanks a lot @sraase!

**Comment by rafael2k** [comment]
And indeed, we are all grateful to Glenn. Btw, do you know if there is an official arache github repo?

**Comment by sraase** [comment]
You can treat this repository as official for now.

I've contacted both Glenn and Michael about it, they are aware and have endorsed it.

To my knowledge, this is the first 'true' repository.

The Arachne project never used version control. I've created some form of linear development history (see tags until "v1.99") based on the ZIP/RAR files I found on Glenn's server, but it is neither accurate nor complete. After the 1.73 GPL release, many people ran their own versions of the code, so development was no longer linear.

I somewhat followed Glenn's development and included what I thought made most sense. Timestamps are set to the release date.

Note that I changed the original files to make them easier to work with (renaming to lower-case, changing line endings, etc.)

**Comment by rafael2k** [comment]
Got it. Thanks a lot!
